name: AutomaticTesting
run-name: ${{ github.actor }} is pushing.

permissions:
  contents: write
  
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.414
      - name: Execute Test
        run: dotnet test --no-build

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.414
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        
  preprelease:
    name: Prep Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  release:
    name: RELEASE
    needs: preprelease

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.414
          
      - name: Publish and Package  
        shell: bash
        run: | 
          release_name="Chirp-${{ github.ref_name }}-${{ matrix.os }}"

          dotnet publish "src/Chirp.CLI/Chirp.CLI.csproj" -r "${{ matrix.os }}" -o "${release_name}" --sc false -p:PublishSingleFile=True

          7z a "${release_name}.zip" "${release_name}/."
          7z d "${release_name}.zip" "*.pdb"

          rm -r "${release_name}"

      - name: Populate GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Chirp-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
